# Generated by Django 2.2.6 on 2019-10-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_telugu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_telugu',
            name='url_title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_telugu',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
