# Generated by Django 2.2.6 on 2019-10-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_telugu', '0002_auto_20191008_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_telugu',
            name='url_title',
        ),
        migrations.AddField(
            model_name='news_telugu',
            name='telugu_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news_telugu',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
