# Generated by Django 2.2.6 on 2019-10-06 06:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('home_Page_Order_1_to_5', models.IntegerField(blank=True, null=True)),
                ('Enable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('rating', models.CharField(choices=[('1', '1'), ('1.25', '1.25'), ('1.5', '1.5'), ('1.75', '1.75'), ('2', '2'), ('2.25', '2.25'), ('2.5', '2.5'), ('2.75', '2.75'), ('3', '3'), ('3.25', '3.25'), ('3.5', '3.5'), ('3.75', '3.75'), ('4', '4'), ('4.25', '4.25'), ('4.5', '4.5'), ('4.75', '4.75'), ('5', '5')], default='', max_length=2)),
            ],
            options={
                'verbose_name': 'reviews',
                'verbose_name_plural': 'reviews',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=200)),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Categories')),
            ],
            options={
                'verbose_name': 'videos',
                'verbose_name_plural': 'videos',
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.CharField(max_length=500, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('Popular_News', models.BooleanField(default=False)),
                ('Banner_News', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Categories')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'news',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Categories')),
            ],
            options={
                'verbose_name': 'images',
                'verbose_name_plural': 'images',
                'db_table': 'images',
            },
        ),
    ]
