# Generated by Django 2.2.6 on 2019-10-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20191006_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('1.25', '1.25'), ('1.5', '1.5'), ('1.75', '1.75'), ('2', '2'), ('2.25', '2.25'), ('2.5', '2.5'), ('2.75', '2.75'), ('3', '3'), ('3.25', '3.25'), ('3.5', '3.5'), ('3.75', '3.75'), ('4', '4'), ('4.25', '4.25'), ('4.5', '4.5'), ('4.75', '4.75'), ('5', '5')], default='', max_length=5),
        ),
    ]
